
### get all users
GET http://localhost:3000/api/v1/users

###upload image by user id
POST http://localhost:3000/api/v1/info/2

### update password
PUT http://localhost:3000/api/v1/users/password/2


### uusi kirjautuminen
POST http://localhost:3000/api/v1/users/login
Content-Type: application/json

{
"tunnus": "anna", "salasana": "123"
}

###get user by username
GET http://localhost:3000/api/v1/users/name/anna

### delete user by user_id
GET http://localhost:3000/api/v1/users/info/71



###uusi user ilman photo
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "firstname": "Lali",
    "lastname": "Viisku",
    "username": "iisin",
    "password": "12345",
    "photo": ""

}


### uusi user
POST http://localhost:3000/api/v1/users
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="firstname"

Anna
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="lastname"

Ansku
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="username"

anna
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"

123
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photo"; filename="cat.jpeg"
Content-Type: image/jpeg

< kuvat/cat.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### update user info
PUT http://localhost:3000/api/v1/users/info/71
Content-Type: application/json

{
  "etunimi": "Heidi",
  "sukunimi": "Pappila",
  "tunnus": "squirrel",
  "email": "squirrel@metropolia.fi",
  "puhelin": "123456789"
}

### update user password
PUT http://localhost:3000/api/v1/users/password/71
Content-Type: application/json

{
  "salasana": "squirrel22"
}

